language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest

after_success:
  - python build.py

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: website
  github-token: $GITHUB_TOKEN
  local-dir: html
  committer-from-gh: true